### ISSUE TITLE
VsgPoints application name creates duplication naming issue in Visual Studio.

### ISSUE THREAD

**Issue by jamierobertson1** [vsg-dev/vsgPoints#19]
Visual studio gives an error on opening the VsgPoints solution "Cannot open item with duplicate name", complaining about the VsgPoints  application having the same name as the VsgPoints library in the same solution and consequently does not load the VsgPoints application. Observed in VS2019 and VS2022. 

Any chance of renaming the VsgPoints application to get around this?

Best regards

Jamie

**Comment by jamierobertson1** [comment]
Yes, not the best but at least it would work. I suspect this isn't getting fixed in VS anytime soon. If it helps I can submit a PR to change it to "vsgpoints_example"?

**Comment by robertosfield** [comment]
Yes go ahead with a PR to change the name to vsgpoints_examples.  The README.md would need updating as well.

It's bizarre that it's 2024 and MS still can't not do some very basic things right.
